### ISSUE TITLE
"0" (zero) glyph off by 1 pixel

### ISSUE THREAD

**Issue by iiiGerardoiii** [kika/fixedsys#12]
![image](https://user-images.githubusercontent.com/6264194/32745538-a6d2bc86-c878-11e7-87f5-a588993b5082.png)
![zerooff](https://user-images.githubusercontent.com/6264194/32746205-7ed482c6-c87a-11e7-9da1-1239a6915ff0.png)

**Comment by kika** [comment]
thanks for reporting, fixed now
