### ISSUE TITLE
Doesnt work on vscode

### ISSUE THREAD

**Issue by Kaffiend** [kika/fixedsys#14]
Doesnt seem to be working on vscode anymore.

**Comment by Kaffiend** [comment]
updated settings required for vscode to use with new font package name. Quotes are required aswell
```
"editor.fontFamily": "'Fixedsys Excelsior 3.01'",
"editor.fontSize": 15,
"editor.fontLigatures": true,
```

**Comment by kika** [comment]
Added to README, thanks!

**Comment by Kaffiend** [comment]
No, thank you! I've been searching for my old favorite fixedsys font for my new editor and the ligatures are a nice bonus!
