### ISSUE TITLE
Not playing nice with MacVim

### ISSUE THREAD

**Issue by benjaminmordaunt** [kika/fixedsys#16]
I've entered:
```
set guifont=Fixedsys\ Excelsior:h16
set noanti
set macligatures
```

into .gvimrc but MacVim seems to not like the ligatures one bit.
<img width="73" alt="image" src="https://user-images.githubusercontent.com/17656637/42834845-ae2325a0-89ef-11e8-86b9-f92566e59c84.png">
Ligatures don't line up and they superimpose one another.

**Comment by iiiGerardoiii** [comment]
Does it work well with other fonts that have ligatures?

**Comment by kika** [comment]
There's some regression in MacVim regarding ligatures. Everything above 8.1-146 doesn't render this font reliably. I'm going to look into this, but not very soon. You can try to open MacVim issue and see what they say there. For myself I just `brew pin` the version at 8.1-146 and called it a day until I have more time to investigate.

**Comment by kika** [comment]
~I've updated to 8.1-153 and font works fine for me~

No, wishful thinking detected

**Comment by kika** [comment]
I've tried to fix this in MacVim for a couple of days but failed, I don't know about CoreText enough to do anything meaningful. I've found a workaround, but you need to rebuild MacVim.
See the issue in MacVim repo https://github.com/macvim-dev/macvim/issues/841

**Comment by kika** [comment]
Seems that MacVim people fixed that
