### ISSUE TITLE
It seems not really monospace in some case

### ISSUE THREAD

**Issue by RRTW** [kika/fixedsys#18]
Below is my screenshots as an animated GIF, you can see how the cursor moved in just up / down key pressed.
![fixedsys_excelsior_not_monospace](https://user-images.githubusercontent.com/5241485/45476155-d4d8d380-b770-11e8-9e48-ff82e3f3c8d5.gif)

Could it be a BOLD text issue ?

Windows7 x32, Notepad++ with Obsidian theme and fixedsys excelsior 3.01

**Comment by iiiGerardoiii** [comment]
> Could it be a BOLD text issue ?

ah yes, the font in bold adds horizontal pixels per character. Disable bold text in the settings maybe?

![45476155-d4d8d380-b770-11e8-9e48-ff82e3f3c8d5](https://user-images.githubusercontent.com/6264194/45497535-b0afcf00-b73d-11e8-95e1-4eaf7b969851.png)

Also, your font looks slightly blurry, and some characters look weird. Is the font size set to 12?

**Comment by kika** [comment]
Right, the bold doesn't work with this font. It is a *simulation* of the bitmapped font by making boxy curves appear as pixels.  So when the font renderer makes the bold it just expands these boxes, but this doesn't visually work in the majority of situations. Bitmapped fonts have different bitmaps for bold, italic, etc, but this font doesn't actually have any bitmaps.
