### ISSUE TITLE
A Issue on the new Windows Terminal

### ISSUE THREAD

**Issue by GEEKiDoS** [kika/fixedsys#19]
![issue](https://user-images.githubusercontent.com/14933408/57568248-38f28b00-7417-11e9-9868-210aff306ef2.gif)

Don't know this caused by this font or by windows terminal, I raised issue on both repo
https://github.com/microsoft/Terminal/issues/696

**Comment by DHowett-MSFT** [comment]
This is definitely Terminal's fault, not the font. You can feel free to close this one :smile:.

**Comment by kika** [comment]
Yep, seems to be the terminal bug. @GEEKiDoS did you try some other font with ligatures like Fira Code?

**Comment by GEEKiDoS** [comment]
> Yep, seems to be the terminal bug. @GEEKiDoS did you try some other font with ligatures like Fira Code?

No, other font with ligatures like Fira code don't have this issue, so I don't know this caused by this font or by windows terminal.

![issue1](https://user-images.githubusercontent.com/14933408/57577001-f1641180-749f-11e9-8ebb-9c50151f09f0.gif)

**Comment by kika** [comment]
Then I'd say it's them both together. Something in the font (being fixed width cells, for example) triggers this behaviour. I'll keep it open until MS opensources windows and we'll have a look at the source :-) Or some other windows app with source available will experience this problem.

**Comment by GEEKiDoS** [comment]
> Then I'd say it's them both together. Something in the font (being fixed width cells, for example) triggers this behaviour. I'll keep it open until MS opensources windows and we'll have a look at the source :-) Or some other windows app with source available will experience this problem.

the new Windows Terminal and old ConHost is opened source with MIT license

**Comment by kika** [comment]
Oh, that's cool, I could probably give it a shot then, once I build back my Windows machine.

**Comment by GEEKiDoS** [comment]
forgot to close this
