### ISSUE TITLE
Is this font free for commercial use?

### ISSUE THREAD

**Issue by ricvail** [kika/fixedsys#21]
Hello. The website is down, and I can't find this information anywhere else.
I would like to use this font (actually the plain font, without ligatures) inside an app, which I intend to sell. Am I allowed to do so? How can I contact the font creator?

**Comment by kika** [comment]
I've sent the link to this issue to the original author and hope he responds. Other than that I don't really know the answer.

**Comment by bathos** [comment]
Hi @ricvail. I made the original Fixedsys Excelsior when I was a teenager. Yes, the site is gone now and probably won’t be back. The font is intended to be free to use and alter as you see fit. Many people have used it in other software and media over the years (kinda cool!).

Possibly notable: the letterforms for the ASCII-range characters are based on the original Fixedsys bitmap font, which is much older and was not created by me. It is not derived from the older font in the software sense though.

**Comment by kika** [comment]
@bathos Thanks!

**Comment by ricvail** [comment]
Great, thank you so much @bathos !

**Comment by jengelh** [comment]
> The font is intended to be free to use and alter as you see fit.

I am considering to include this in a Linux distribution. For that to practically work, interested parties would, as I understand it, also need permission to distribute and sublicense besides "use and alter". To make a long story short, there is an established license text for such, the OFL ([wikipedia](https://en.wikipedia.org/wiki/SIL_Open_Font_License), [legal text](https://scripts.sil.org/cms/scripts/page.php?item_id=OFL)). Would you be willing to provide FixedsysExcelsior under its terms?

> Possibly notable: the letterforms for the ASCII-range characters are based on the original Fixedsys bitmap font, which is much older and was not created by me. It is not derived from the older font in the software sense though.

int10h.org evaluated a similar concern and posted [a conclusion in their FAQ](https://int10h.org/oldschool-pc-fonts/readme/). int10h's oldschoolpc-fonts pack has found its way into Linux distros, so is fine by the looks of it.

**Comment by kika** [comment]
@jengelh According to @bathos the font is essentially in the public domain, my changes are free too. I'm not into that toxic GPL crap, so as far as the license is not contagious I'm okay with it. From the wikipedia link it appears that it's not. If you need some specific wording to be included somewhere (README or elsewhere) you are welcome to submit PR. 
The only limitation is that this license should not become exclusive. The original "license" is public domain, and it has to remain such.
