### ISSUE TITLE
Can we get a version where <= gets replaced with ≤ instead of ⇐?

### ISSUE THREAD

**Issue by JobLeonard** [kika/fixedsys#3]
.. and have a `>=` to ≥ conversion too, while we're at it :).

I'm not going to ask you to remove the existing version, since I assume you added it because it fits your use-case best. However, the inequality cases actually show up in my code, whereas there is no context where ⇐ actually means something. So that's why I'd rather have a version with inequality ligatures.

**Comment by kika** [comment]
I knew I will get this request some day :-) 
You want <= to be replaced with ≤ and >= with ≥ while => stays a fat arrow?

**Comment by JobLeonard** [comment]
I use a few languages with fat arrows so yeah, that would suit my particular use-case best (despite the asymmetry).

**Comment by kika** [comment]
New 3.02.7 -Alt version is for you.

Glyphs are modeled after Fira Code (I can't use unicode glyphs directly, they are single cell and >= takes 2 char cells).

**Comment by JobLeonard** [comment]
I love it, thank you so much!
