### ISSUE TITLE
Powerline Glyph

### ISSUE THREAD

**Issue by ragnarov** [kika/fixedsys#32]
Heya,
I have created two powerline glyphs for Fixedsys.
Probably will add some more in future.
I did this with fontforge.
I can't say I knew what I was doing xD
Should I submit a pull request?
You will find it here : https://github.com/ragnarov/fixedsys-powerline

**Comment by kika** [comment]
If it's a clean diff just adding these symbols without conflicts with any other and without touching the font metadata outside the symbols then I see no objections for the PR

**Comment by ragnarov** [comment]
Oh, thank you.
I will be back in a few months.
Till then bye. :)
