### ISSUE TITLE
No-ligiature version for terminals

### ISSUE THREAD

**Issue by zulc22** [kika/fixedsys#35]
While the main feature of Fixedsys Excelsior is that it has ligatures for coding, TUI elements in terminals, especially progress bars as seen in `cargo` ("`[====>    ]`") can look really bad. I don't believe any other version of 'Fixedsys' would be good to switch to in an attempt to solve the problem myself because of all those extra unicode symbols that are very helpful with TUI elements that use unicode, e.g. `yarn`.

**Comment by kika** [comment]
You can always produce the version that suits your particular needs by removing offending ligature sections from the XML file and recompiling. Maintaining the alt version is one too many already :-)

**Comment by stianhoiland** [comment]
+1 for this feature. I do not think I will ever live without Fixedsys and having a terminal-robust version would be great.
