### ISSUE TITLE
Add nerd-font support

### ISSUE THREAD

**Issue by NEX-S** [kika/fixedsys#36]
this is an awesome font!!!! I love it!!!!

if it can support the nerd-font that would be fantastic!!!!

**Comment by kika** [comment]
You mean this https://github.com/ryanoasis/nerd-fonts ? It will take an insane amount of work, because just "patching" the font is not enough, the icon glyphs should be redesigned with the blocky appearance specific for the Fixedsys. AI can probably do it semi-automagically, but someone needs to find a model and then train it. 
I'll keep the issue open, but I personally do not have resources to engage in this titanic effort.

**Comment by NEX-S** [comment]
> It will take an insane amount of work

as far as i know, all the nerd-fonts is just patching the same set of icons into the .ttf files ( i tried some nerd-font and seems the icon in the font is the same, the difference between them seems is just 0-9a-zA-Z and the punctuations)

> "patching" the font is not enough,

actually I tried to use Fontfrog to merge the nerd-font icon into the fixedsys, ( i’m not sure if the way i’m using fontfrog was right, it’s my first time changing the .ttf file ) it works well for me. the nerd-font icon is showing exactly the way i wish.

> the icon glyphs should be redesigned with the blocky appearance specific for the Fixedsys.

as your mentioned, It will take an insane amount of work 😱

**Comment by kika** [comment]
You're right, if someone wants to put foreign-looking icons in the font - they can follow the guide in the nerd-fonts repo and patch for themselves. But doing it right is a lot of work, but who knows, someone may pick it up.

**Comment by squallliu** [comment]
https://github.com/delinx/Fixedsys-Modern

**Comment by kika** [comment]
Out of curiosity I tried to use the Nerd Fonts patcher with default settings and it completely screws up the font. Dunno what I did wrong, but it doesn't seem as easy as presented. If someone succeeds in merging Fixedsys with Nerd icons then please describe the process (as a PR to README.md or just in the comments)

**Comment by gusbemacbe** [comment]
@NEX-S and @kika, if you want to keep this font minimal and with a minimal job, following Arch Linux's KISS philosophy, you can inspire on @slavfox's [Cozette](https://github.com/slavfox/Cozette), totally compatible with Powerline, and with @romkatv's Powerlevel10k.

**Comment by kika** [comment]
apparently `font-patcher` works fine now with the font. I used the `font-patcher -s -c FSEX302.ttf` and the resulting font appears to work fine. `-c` makes the font much bigger, but without it some of the `nvim-web-devicons` were not rendering.
I'm closing for now.
