### ISSUE TITLE
Font cannot be used in VSCode

### ISSUE THREAD

**Issue by ghost** [kika/fixedsys#38]
I tried everything, i put everything as the guide says here, however, i couldn't use, the VSCode didn't load that

**Comment by kika** [comment]
As you can see in the screenshot - it works. 
<img width="534" alt="image" src="https://user-images.githubusercontent.com/207889/235196715-86804735-21e6-4442-8cc5-42803a3e2178.png">

Relevant settings (VSCode on Mac): 
```json
{
    "debug.console.fontFamily": "Fixedsys Excelsior",
    "debug.console.fontSize": 16,
    "debug.console.lineHeight": 19,
    "workbench.fontAliasing": "none",
    "terminal.integrated.fontFamily": "Fixedsys Excelsior",
    "terminal.integrated.fontSize": 16,
    "editor.fontFamily": "Fixedsys Excelsior",
    "editor.fontLigatures": true,
    "editor.fontSize": 16,
    "editor.lineHeight": 16
}
```

**Comment by shadowfoxish** [comment]
For folks coming here wondering why it maybe isn't working in VS Code, try editing the settings file directly. The UI seemed to be blocking me from using the Fixedsys Excelsior 3.01 on the terminal claiming it isn't monospaced, but editing it in the settings file seems to work just fine. Also, font size 16 seemed to be the correct pixel-perfect fontSize, at least for me.
![image](https://github.com/user-attachments/assets/78b6dd88-91f2-4b69-ad83-08a8738d248b)

**Comment by unennhexium** [comment]
@kika, there no ligatures in integrated terminal. How to enable it?

Here is my setting

```jsonc
"terminal.integrated.fontFamily": "'Fixedsys Excelsior'"
"terminal.integrated.fontLigatures.enabled": true
"terminal.integrated.fontLigatures.featureSettings": "\"liga\" on",
```

<details>
    <summary>
        and screenshot
    </summary>
<img width="259" height="927" alt="Image" src="https://github.com/user-attachments/assets/86896b1b-5ca3-417d-bd1e-9c6381d6bac0" />
</details>
