### ISSUE TITLE
<== ligature

### ISSUE THREAD

**Issue by ForNeVeR** [kika/fixedsys#6]
I think that `<==` operator should get its own ligature. Some languages permit to define it (personally I often see it with Scala and ScalaFX, it's the standard binding operator there). It looks terrible with `FSEX302-alt.ttf` (as ` ≤=` instead of `<==`), but I don't think it would look nice even with the "default" `FSEX302.ttf`.

**Comment by kika** [comment]
Makes sense, will add

**Comment by kika** [comment]
Closed by https://github.com/kika/fixedsys/releases/tag/v3.02.8

**Comment by ForNeVeR** [comment]
Wow, thank you!
