### ISSUE TITLE
Use the first PUA block

### ISSUE THREAD

**Issue by adrianparvino** [kika/fixedsys#9]
Higher PUA blocks don't seem to work under Emacs and st. I'm willing to give instructions for getting it to work under Emacs.

**Comment by kika** [comment]
I'd appreciate a PR for the readme file explaining how to make it work for Emacs. Thanks!

**Comment by adrianparvino** [comment]
#10 There are some things not yet added such as ++, it was just a late night hack. Maybe I should make it a package.

**Comment by kika** [comment]
Excellent, thanks a lot!

**Comment by s5bug** [comment]
Still doesn't want to work for me:
![image](https://user-images.githubusercontent.com/7751296/62406997-2b582780-b566-11e9-8d4b-420397824513.png)
Also, some don't even ligature:
![image](https://user-images.githubusercontent.com/7751296/62407016-9b66ad80-b566-11e9-88bc-33855a92b7d6.png)
